# Generated by Django 5.0.2 on 2024-04-07 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TodoApp', '0002_todolist_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('completed', models.IntegerField()),
                ('incompleted', models.IntegerField()),
            ],
        ),
    ]
